name: Publish Legacy Images

########################################################
#
# Builds qBittorrent v4.1.0 thru v4.2.5
#
########################################################

on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: rmartin16
  IMAGE_NAME: qbittorrent-nox

jobs:

  libtorrent-versions:
    uses: ./.github/workflows/libtorrent-latest-versions.yml

  build:
    runs-on: ubuntu-latest
    needs: libtorrent-versions
    permissions:
      contents: read
      packages: write
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        QBITTORRENT_VERSION: [ "4.1.0","4.1.1","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.1.7","4.1.8","4.1.9","4.1.9.1","4.2.0","4.2.1","4.2.2","4.2.3","4.2.4","4.2.5" ]
        QBITTORRENT_BUILD_TYPE: [ "release", "debug" ]
        include:
          - LIBTORRENT_VERSION: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
            LIBTORRENT_TAG: "v1"
          - LIBTORRENT_VERSION: "1_1_14"
            LIBTORRENT_TAG: "1_1_14"
          - QBITTORRENT_VERSION: "4.2.0"
            LIBTORRENT_VERSION: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
            LIBTORRENT_TAG: "v1"
          - QBITTORRENT_VERSION: "4.2.1"
            LIBTORRENT_VERSION: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
            LIBTORRENT_TAG: "v1"
          - QBITTORRENT_VERSION: "4.2.2"
            LIBTORRENT_VERSION: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
            LIBTORRENT_TAG: "v1"
          - QBITTORRENT_VERSION: "4.2.3"
            LIBTORRENT_VERSION: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
            LIBTORRENT_TAG: "v1"
          - QBITTORRENT_VERSION: "4.2.4"
            LIBTORRENT_VERSION: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
            LIBTORRENT_TAG: "v1"
          - QBITTORRENT_VERSION: "4.2.5"
            LIBTORRENT_VERSION: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
            LIBTORRENT_TAG: "v1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
          flavor: latest=false
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.title=qbittorrent-nox
            org.opencontainers.image.description=Headless qBittorrent v${{ matrix.QBITTORRENT_VERSION }} using libtorrent ${{ matrix.LIBTORRENT_VERSION }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
          tags: |
            # v4.2.5 - specific qBittorrent with latest v1 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VERSION }},enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' }}
            # v4.2.5-v1 - specific qBittorrent with specific libtorrent version
            type=raw,value=v${{ matrix.QBITTORRENT_VERSION }}-v1,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' }}
            # v4.2.5-debug - specific debug qBittorrent with latest v1 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VERSION }}-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' }}
            # v4.2.5-v1-debug - specific debug qBittorrent with specific libtorrent version
            type=raw,value=v${{ matrix.QBITTORRENT_VERSION }}-v1-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          file: All.Legacy.Dockerfile
          target: release
          context: .
          load: true
          cache-from: type=gha,scope=${{ matrix.LIBTORRENT_TAG }}-legacy
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LIBTORRENT_VERSION=${{ matrix.LIBTORRENT_VERSION }}
            QBT_VERSION=${{ matrix.QBITTORRENT_VERSION }}
            QBT_BUILD_TYPE=${{ matrix.QBITTORRENT_BUILD_TYPE }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Verify image
        run: |
          DOCKER_TAG=v${{ matrix.QBITTORRENT_VERSION }}-v1
          if [[ "${{ matrix.QBITTORRENT_BUILD_TYPE }}" = "debug" ]]; then DOCKER_TAG="${DOCKER_TAG}-debug"; fi
          docker run -d --name qbt -p8080:8080 ${REGISTRY}/${REGISTRY_USER}/${IMAGE_NAME}:${DOCKER_TAG}
          python -m pip install qbittorrent-api
          docker logs qbt
          python -c 'from qbittorrentapi import Client; client=Client("localhost",8080,"admin","adminadmin"); print(f"{client.app.version=}"); assert client.app.version=="v${{ matrix.QBITTORRENT_VERSION }}"'
          docker exec qbt /bin/sh -c "tail -n+1 /build_commit.*"

      - name: Publish image to ghcr.io
        if: github.event_name != 'pull_request'
        run: docker push --all-tags ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
