name: Publish Release Images

########################################################
#
# Builds qBittorrent v4.3.0+
#
########################################################

on:
  schedule:
    - cron: "36 6 */7 * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rmartin16/qbittorrent-nox
  CACHE_VER: "1"

jobs:

  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      qbittorrent-versions: ${{ steps.set-qbittorrent-versions.outputs.qbittorrent-versions }}
      qbittorrent-latest-version: ${{ steps.set-qbittorrent-versions.outputs.qbittorrent-latest-version }}
      libtorrent-v1-version: ${{ steps.set-libtorrent-versions.outputs.libtorrent-v1-version }}
      libtorrent-v2-version: ${{ steps.set-libtorrent-versions.outputs.libtorrent-v2-version }}

    steps:
      - name: Declare qBittorrent Versions
        id: set-qbittorrent-versions
        run: |  # find all releases >= v4.3.0
          ALL_VERS=$( \
            git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/qbittorrent/qBittorrent.git | \
            cut --delimiter='/' --fields=3 | \
            grep -v "\^{}" | \
            cut --delimiter='-' --fields=2 | \
            grep '^4\.[3-9]\.\d*.' \
          )

          FINAL_VERSION_VERS=$( \
            git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/qbittorrent/qBittorrent.git | \
            grep -vE 'beta|rc' | \
            cut --delimiter='/' --fields=3 | \
            grep -v "\^{}" | \
            cut --delimiter='-' --fields=2 | \
            grep '^4\.[3-9]\.\d*.' \
          )

          LATEST_VER=$(echo ${FINAL_VERSION_VERS} | rev | cut -d' ' -f1 | rev)
          echo "Latest: ${LATEST_VER}"
          echo "qbittorrent-latest-version=${LATEST_VER}" >> ${GITHUB_OUTPUT}

          VERS_MATRIX_LIST=$(echo ${ALL_VERS} | sed -z 's/ /","/g;s/,$/\n/')
          VERS_MATRIX_LIST="[\"${VERS_MATRIX_LIST}\"]"
          echo ${VERS_MATRIX_LIST}
          echo "qbittorrent-versions=${VERS_MATRIX_LIST}" >> ${GITHUB_OUTPUT}

      - name: Declare libtorrent Versions
        id: set-libtorrent-versions
        run: |
          LATEST_V2=$( \
            git -c 'versionsort.suffix=-' ls-remote --tags --sort='-v:refname' https://github.com/arvidn/libtorrent.git | \
            cut --delimiter='/' --fields=3 | \
            grep '^v2\.' | \
            head -n1 | \
            sed 's/v//' \
          )
          echo "Latest v2: ${LATEST_V2}"
          echo "libtorrent-v2-version=${LATEST_V2}" >> ${GITHUB_OUTPUT}

          LATEST_V1=$( \
            git -c 'versionsort.suffix=-' ls-remote --tags --sort='-v:refname' https://github.com/arvidn/libtorrent.git | \
            cut --delimiter='/' --fields=3 | \
            grep '^v1\.2' | \
            head -n1 | \
            sed 's/v//' \
          )
          echo "Latest v1: ${LATEST_V1}"
          echo "libtorrent-v1-version=${LATEST_V1}" >> ${GITHUB_OUTPUT}

  build:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        QBITTORRENT_VER: ${{ fromJson(needs.setup.outputs.qbittorrent-versions) }}
        QBITTORRENT_BUILD_TYPE: [ "release", "debug" ]
        LIBTORRENT_VER: [ "${{ needs.setup.outputs.libtorrent-v2-version }}", "${{ needs.setup.outputs.libtorrent-v1-version }}" ]
        include:
          - BOOST_VERSION: "1_80_0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v3
        with:
          path: ./downloads
          key: sources-${{ env.CACHE_VER }}-${{ matrix.BOOST_VERSION }}

      - name: Download sources
        if: steps.cache-sources.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./downloads
          curl -NLk \
            "https://boostorg.jfrog.io/artifactory/main/release/$(echo ${{ matrix.BOOST_VERSION }} | sed 's/_/\./g')/source/boost_${{ matrix.BOOST_VERSION }}.tar.gz" \
            -o "./downloads/boost_${{ matrix.BOOST_VERSION }}.tar.gz"

      - name: Determine Qt Version
        id: qt
        run: |
          echo "version=qt6" >> ${GITHUB_OUTPUT}
          if [[ ${{ matrix.QBITTORRENT_VER }} = 4.3* ]]; then echo "version=qt5" >> ${GITHUB_OUTPUT}; fi
          if [[ ${{ matrix.QBITTORRENT_VER }} = 4.4.0beta* ]]; then echo "version=qt5" >> ${GITHUB_OUTPUT}; fi

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.title=qbittorrent-nox
            org.opencontainers.image.description=Headless qBittorrent v${{ matrix.QBITTORRENT_VER }} with libtorrent v${{ matrix.LIBTORRENT_VER }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
          tags: |
            # latest - latest qBittorrent with latest v2 libtorrent
            type=raw,value=latest,enable=${{ matrix.QBITTORRENT_VER == needs.setup.outputs.qbittorrent-latest-version && matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # latest-v2 - latest qBittorrent with latest v2 libtorrent
            type=raw,value=latest-v2,enable=${{ matrix.QBITTORRENT_VER == needs.setup.outputs.qbittorrent-latest-version && matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # latest-v1 - latest qBittorrent with latest v2 libtorrent
            type=raw,value=latest-v1,enable=${{ matrix.QBITTORRENT_VER == needs.setup.outputs.qbittorrent-latest-version && matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v1-version }}
            # latest-debug - latest debug qBittorrent with latest v2 libtorrent
            type=raw,value=latest-debug,enable=${{ matrix.QBITTORRENT_VER == needs.setup.outputs.qbittorrent-latest-version && matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # latest-v2-debug - latest debug qBittorrent with latest v2 libtorrent
            type=raw,value=latest-v2-debug,enable=${{ matrix.QBITTORRENT_VER == needs.setup.outputs.qbittorrent-latest-version && matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # latest-v1-debug - latest debug qBittorrent with latest v2 libtorrent
            type=raw,value=latest-v1-debug,enable=${{ matrix.QBITTORRENT_VER == needs.setup.outputs.qbittorrent-latest-version && matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v1-version }}
            # v4.4.4 - specific qBittorrent with latest v2 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VER }},enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # v4.4.4-v2 - specific qBittorrent with latest v2 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VER }}-v2,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # v4.4.4-v1 - specific qBittorrent with latest v1 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VER }}-v1,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v1-version }}
            # v4.4.4-debug - specific debug qBittorrent with latest v2 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VER }}-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # v4.4.4-v2-debug - specific debug qBittorrent with latest v2 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VER }}-v2-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v2-version }}
            # v4.4.4-v1-debug - specific debug qBittorrent with latest v1 libtorrent
            type=raw,value=v${{ matrix.QBITTORRENT_VER }}-v1-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_VER == needs.setup.outputs.libtorrent-v1-version }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BOOST_VERSION=${{ matrix.BOOST_VERSION }}
            LIBTORRENT_VERSION=${{ matrix.LIBTORRENT_VER }}
            QBT_VERSION=${{ matrix.QBITTORRENT_VER }}
            QBT_BUILD_TYPE=${{ matrix.QBITTORRENT_BUILD_TYPE }}
            QT_VERSION=${{ steps.qt.outputs.version }}
            CACHEBUST=${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Set up Python
        if: github.event_name != 'pull_request'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Verify image
        if: github.event_name != 'pull_request'
        id: verify
        run: |
          if [[ "${{ matrix.LIBTORRENT_VER }}" = "1."* ]]; then VER="v1"; else VER="v2"; fi
          DOCKER_TAG=v${{ matrix.QBITTORRENT_VER }}-${VER}
          if [[ "${{ matrix.QBITTORRENT_BUILD_TYPE }}" = "debug" ]]; then DOCKER_TAG="${DOCKER_TAG}-debug"; fi
          docker run --rm -d --name qbt -p8080:8080 ${REGISTRY}/${IMAGE_NAME}:${DOCKER_TAG}
          python -m pip install qbittorrent-api
          docker logs qbt
          python -c 'from qbittorrentapi import Client; client=Client("localhost",8080,"admin","adminadmin"); print(f"{client.app.version=}"); assert client.app.version=="v${{ matrix.QBITTORRENT_VER }}"'
