name: Publish Latest Release Image

########################################################
#
# Builds the latest qBittorrent release only
#
########################################################

on:
  workflow_dispatch:
  workflow_call:

jobs:

  libtorrent-versions:
    uses: ./.github/workflows/libtorrent-latest-versions.yml

  qbittorrent-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      qbittorrent-latest-version: ${{ steps.set-qbittorrent-versions.outputs.qbittorrent-latest-version }}

    steps:
      - name: Declare qBittorrent Versions
        id: set-qbittorrent-versions
        run: |  # find the latest final release >= v4.3.0
          FINAL_VERSION_VERS=$( \
            git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/qbittorrent/qBittorrent.git | \
            grep -vE 'alpha|beta|rc' | \
            cut --delimiter='/' --fields=3 | \
            grep -v "\^{}" | \
            cut --delimiter='-' --fields=2 | \
            grep -E '^4\.[3-9]\.\d*.|^[5-9]\.\d*.\.\d*.' \
          )

          LATEST_VER=$(echo ${FINAL_VERSION_VERS} | rev | cut -d' ' -f1 | rev)
          echo "Latest: ${LATEST_VER}"
          echo "qbittorrent-latest-version=${LATEST_VER}" >> ${GITHUB_OUTPUT}

  build:
    needs: [ qbittorrent-versions, libtorrent-versions ]
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/build-images.yml
    with:
      qbittorrent-versions: '["${{ needs.qbittorrent-versions.outputs.qbittorrent-latest-version }}"]'
      qbittorrent-latest-version: ${{ needs.qbittorrent-versions.outputs.qbittorrent-latest-version }}
      version-style: release
      libtorrent-v1-version: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
      libtorrent-v2-version: ${{ needs.libtorrent-versions.outputs.libtorrent-v2-version }}
      libtorrent-v2_1-version: ${{ needs.libtorrent-versions.outputs.libtorrent-v2_1-version }}
