name: Publish Dev Images

########################################################
#
# Builds qBittorrent from dev branches
#
########################################################

on:
  schedule:
    - cron: "36 4 * * *"
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rmartin16/qbittorrent-nox

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        QBITTORRENT_VER: [ "master", "v4_5_x", "v4_4_x", "v4_3_x" ]
        QBITTORRENT_BUILD_TYPE: [ "release", "debug" ]
        LIBTORRENT_TAG: [ "v2", "v1" ]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Qt Version
        id: qt
        run: |
          echo "version=qt6" >> ${GITHUB_OUTPUT}
          if [[ ${{ matrix.QBITTORRENT_VER }} = v4_3* ]]; then echo "version=qt5" >> ${GITHUB_OUTPUT}; fi

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Download base image artifact
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: base-image-libtorrent-${{ matrix.LIBTORRENT_TAG }}
          path: /tmp

      - name: Load base image
        run: |
          if [ -f "/tmp/base-image.tar" ]; then
            docker load --input /tmp/base-image.tar
            docker image ls -a
          fi

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.title=qbittorrent-nox
            org.opencontainers.image.description=Headless qBittorrent ${{ matrix.QBITTORRENT_VER }} with libtorrent ${{ matrix.LIBTORRENT_TAG }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
          tags: |
            # master - specific qBittorrent with latest v2 libtorrent
            type=raw,value=${{ matrix.QBITTORRENT_VER }},enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_TAG == 'v2' }}
            # master-v2 - specific qBittorrent with latest v2 libtorrent
            type=raw,value=${{ matrix.QBITTORRENT_VER }}-v2,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_TAG == 'v2' }}
            # master-debug - specific debug qBittorrent with latest v2 libtorrent
            type=raw,value=${{ matrix.QBITTORRENT_VER }}-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_TAG == 'v2' }}
            # master-v2-debug - specific debug qBittorrent with latest v2 libtorrent
            type=raw,value=${{ matrix.QBITTORRENT_VER }}-v2-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_TAG == 'v2' }}
            # master-v1 - specific qBittorrent with latest v1 libtorrent
            type=raw,value=${{ matrix.QBITTORRENT_VER }}-v1,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'release' && matrix.LIBTORRENT_TAG == 'v1' }}
            # master-v1-debug - specific debug qBittorrent with latest v1 libtorrent
            type=raw,value=${{ matrix.QBITTORRENT_VER }}-v1-debug,enable=${{ matrix.QBITTORRENT_BUILD_TYPE == 'debug' && matrix.LIBTORRENT_TAG == 'v1' }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          file: qBittorrent.Dockerfile
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LIBTORRENT_TAG=${{ matrix.LIBTORRENT_TAG }}
            QBT_VERSION=${{ matrix.QBITTORRENT_VER }}
            QBT_BUILD_TYPE=${{ matrix.QBITTORRENT_BUILD_TYPE }}
            QT_VERSION=${{ steps.qt.outputs.version }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Verify image
        run: |
          DOCKER_TAG=${{ matrix.QBITTORRENT_VER }}-${{ matrix.LIBTORRENT_TAG }}
          if [[ "${{ matrix.QBITTORRENT_BUILD_TYPE }}" = "debug" ]]; then DOCKER_TAG="${DOCKER_TAG}-debug"; fi
          docker run --rm -d --name qbt -p8080:8080 ${REGISTRY}/${IMAGE_NAME}:${DOCKER_TAG}
          python -m pip install qbittorrent-api
          docker logs qbt
          python -c 'from qbittorrentapi import Client; client=Client("localhost",8080,"admin","adminadmin"); print(f"{client.app.version=}")'

      - name: Publish image to ghcr.io
        if: github.event_name != 'pull_request'
        run: docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
