name: Publish Dev Images

########################################################
#
# Builds qBittorrent from dev branches
#
########################################################

on:
  schedule:
    - cron: "36 4 */2 * *"
  workflow_dispatch:
  workflow_call:

jobs:

  libtorrent-versions:
    uses: ./.github/workflows/libtorrent-latest-versions.yml

  build:
    needs: libtorrent-versions
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/build-images.yml
    with:
      qbittorrent-versions: '["master", "v5_2_x", "v5_1_x", "v5_0_x", "v4_6_x", "v4_5_x", "v4_4_x", "v4_3_x"]'
      version-style: branch
      libtorrent-v1-version: ${{ needs.libtorrent-versions.outputs.libtorrent-v1-version }}
      libtorrent-v2-version: ${{ needs.libtorrent-versions.outputs.libtorrent-v2-version }}
      libtorrent-v2_1-version: ${{ needs.libtorrent-versions.outputs.libtorrent-v2_1-version }}
