name: Declare Latest Libtorrent Versions

on:
  workflow_call:
    outputs:
      libtorrent-v1-version:
        description: "Most recent version of libtorrent v1"
        value: ${{ jobs.libtorrent-versions.outputs.libtorrent-v1-version }}
      libtorrent-v2-version:
        description: "Most recent version of libtorrent v2"
        value: ${{ jobs.libtorrent-versions.outputs.libtorrent-v2-version }}

jobs:

  libtorrent-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      libtorrent-v1-version: ${{ steps.set-libtorrent-versions.outputs.libtorrent-v1-version }}
      libtorrent-v2-version: ${{ steps.set-libtorrent-versions.outputs.libtorrent-v2-version }}

    steps:
      - name: Declare libtorrent Versions
        id: set-libtorrent-versions
        run: |
          LATEST_V2=$( \
            git -c 'versionsort.suffix=-' ls-remote --tags --sort='-v:refname' https://github.com/arvidn/libtorrent.git | \
            cut --delimiter='/' --fields=3 | \
            grep '^v2\.' | \
            head -n1 | \
            sed 's/v//' \
          )
          echo "Latest v2: ${LATEST_V2}"
          echo "libtorrent-v2-version=${LATEST_V2}" >> ${GITHUB_OUTPUT}

          LATEST_V1=$( \
            git -c 'versionsort.suffix=-' ls-remote --tags --sort='-v:refname' https://github.com/arvidn/libtorrent.git | \
            cut --delimiter='/' --fields=3 | \
            grep '^v1\.2' | \
            head -n1 | \
            sed 's/v//' \
          )
          echo "Latest v1: ${LATEST_V1}"
          echo "libtorrent-v1-version=${LATEST_V1}" >> ${GITHUB_OUTPUT}
